version: "3"

services:
  leagueabuserbackend:
    container_name: "LeagueAbuserBackend"
    image: sandrospengler/leagueabuserbackend
    build:
      context: .
    environment:
      - PORT=5000
    networks:
      - LeagueAbuserNetwork
