version: "3"

services:
  leagueabuserbackend:
    container_name: "LeagueAbuserBackend"
    image: sandrospengler/leagueabuserbackend
    build:
      context: ${LeagueAbuserBackend}
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - DB_CONNECTION=${DB_CONNECTION_LEAGUE}
      - VIRTUAL_HOST=leagueabuser.axfert.com
      - LETSENCRYPT_HOST=leagueabuser.axfert.com
    command: npm run prod
