FROM node:19.0.1-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./package.json /usr/src/app
# RUN rm -r /usr/src/app/build
ARG NODE_ENV
RUN npm install --only=production;
COPY . /usr/src/app
EXPOSE 5000
CMD ["npm","run","prod"]