version: "3"

services:
  leagueabuserbackend:
    container_name: "LeagueAbuserBackend"
    image: sandrospengler/leagueabuserbackend:latest
    build:
      context: .
    environment:
      - PORT=5000
    networks:
      - LeagueAbuserNetwork
      - LeagueMongoDBNetwork
    restart: always

  leaguemongo:
    container_name: "LeagueMongoMain"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=""
      - MONGO_INITDB_ROOT_PASSWORD=""
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - LeagueMongoDBNetwork
    restart: always

networks:
  LeagueMongoDBNetwork:
