version: "3"

services:
  eloinflater:
    container_name: "Eloinflater"
    # image: sandrospengler/eloinflater:latest
    build:
      context: .
    environment:
      - PORT="1337"
    networks:
      - LeagueAbuserNetwork
      - LeagueMongoDBNetwork
    restart: always

  leaguemongo:
    container_name: "LeagueMongoMain"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=""
      - MONGO_INITDB_ROOT_PASSWORD=""
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - LeagueMongoDBNetwork
    restart: always

networks:
  LeagueMongoDBNetwork:
