version: "3"

services:
  leagueabuserbackend:
    container_name: "LeagueAbuserBackend"
    # image: sandrospengler/leagueabuserbackend:latest
    build:
      context: ${LeagueAbuserBackend}
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - RUN_JOB=${RUN_JOB}
      - API_KEY=${API_KEY}
      - DB_CONNECTION=${DB_CONNECTION_LEAGUE}
      - VIRTUAL_HOST=eloinflater.axfert.com
      - LETSENCRYPT_HOST=eloinflater.axfert.com
    command: npm run prod

  leaguemongo:
    container_name: "LeagueMongoPi"
    image: mongo:bionic
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/External/Databases/MongoDBLeague/data:/data/db
      - ~/External/Databases/Backup/MongoDBLeague:/Backup
    networks:
      - LeagueMongoDBNetwork
