version: "3"

services:
  eloinflater:
    container_name: "Eloinflater"
    #image: sandrospengler/eloinflater:latest
    build:
      context: ${Eloinflater}
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - RUN_JOB=${RUN_JOB}
      - API_KEY=${API_KEY}
      - DB_CONNECTION=${DB_CONNECTION_LEAGUE}
      - LOGGLY_TOKEN=${LOGGLY_TOKEN}
      - NODE_OPTIONS=--max_old_space_size=6144
    command: npm run prod
    volumes:
      - ~/Logs/Eloinflater:/usr/src/app/Logs

  leaguemongo:
    container_name: "LeagueMongoProd"
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/External/Databases/MongoDBLeague/data:/data/db
      - ~/External/Databases/Backup/MongoDBLeague:/Backup
