version: "3"

services:
  leagueabuserbackend:
    container_name: "LeagueAbuserBackend"
    image: sandrospengler/leagueabuserbackend
    build:
      context: ${LeagueAbuserBackend}
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - RUN_JOB=${RUN_JOB}
      - API_KEY=${API_KEY}
      - DB_CONNECTION=${DB_CONNECTION_LEAGUE}
      - NODE_OPTIONS=--max_old_space_size=6144
    command: npm run prod
